### ISSUE TITLE
zephyr 知识点梳理

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/bluetoothlover_doc#504]
zephyr配置和编译系统

- [ ] Kconfig
- [ ] devicetree
- [ ] cmake
- [ ] config和build 的流程梳理，pre-build， 中间二进制等
- [ ] sysbuild等

**Comment by supperthomas** [comment]
zephyr 代码流程

- [ ] 如何添加一个新的bsp开发板，类似的stm32的
- [ ] 如何添加一个新的SOC的驱动，比如UART gpio等
- [ ]

**Comment by supperthomas** [comment]
https://docs2.listenai.com/x/krXhU-28YlR

参考文档

**Comment by supperthomas** [comment]
环境搭建：
https://docs2.listenai.com/x/ZgVUIzY6M

**Comment by supperthomas** [comment]
PR点：
zephyr\samples\subsys\ipc\ipc_service\icmsg\boards\nrf5340dk_nrf5340_cpuapp.overlay   地址大小不对

**Comment by supperthomas** [comment]
```
[        cmd = (](https://github.com/zephyrproject-rtos/zephyr/blob/5d4a116c44412e5ba15f9c56d2dc465746d7d3b0/scripts/west_commands/runners/jlink.py#L545)
```

**Comment by supperthomas** [comment]
bs_nrf52_bsim_samples_bluetooth_peripheral => bs_nrf52_bsim_samples_bluetooth_peripheral_hr

**Comment by supperthomas** [comment]
🏗️ 核心系统组件
picolibc: 轻量级 C 库
cmsis/cmsis-dsp/cmsis-nn: ARM 标准接口和算法库
mcuboot: 安全引导加载器
🔗 硬件抽象层 (HAL)
支持 20+ 厂商的 MCU/SoC
涵盖 ARM、RISC-V、Xtensa 等架构
从低功耗 MCU 到高性能 SoC
🌐 网络和通信
WiFi: hostap, nrf_wifi
蓝牙: BabbleSim 仿真, libsbc, liblc3
LoRa/Thread: loramac-node, openthread
安全通信: mbedtls, uoscore-uedhoc
💾 存储和文件系统
fatfs: 传统 FAT 文件系统
littlefs: 嵌入式 Flash 文件系统
🔒 安全和加密
mbedtls: 完整加密库
tinycrypt: 轻量级加密
trusted-firmware: ARM 安全固件
🎵 音频和多媒体
liblc3: BLE Audio 编解码
libsbc: 经典蓝牙音频
lvgl: 图形用户界面
🔧 调试和测试
BabbleSim: 蓝牙仿真框架
segger/percepio: 专业调试工具
edtt/net-tools: 测试工具集

**Comment by supperthomas** [comment]
```
# The west manifest file for upstream Zephyr.

manifest:
  defaults:
    remote: zns-modules

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim
    - name: zns-modules
      url-base: http://gitlab.zgmicro.com/zgmbt/zns/modules

  group-filter: [-babblesim, -optional]

  projects:
    # ========== 标准库和系统组件 ==========
    - name: acpica
      revision: 8d24867bc9c9d81c81eeac59391cda59333affd4
      path: modules/lib/acpica
      # ACPI Component Architecture - ACPI 系统接口实现，用于 x86 平台的电源和配置管理

    - name: picolibc
      path: modules/lib/picolibc
      revision: 560946f26db075c296beea5b39d99e6de43c9010
      # 轻量级 C 标准库，专为嵌入式系统设计，替代 newlib，减少内存占用

    - name: tinycrypt
      revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
      path: modules/crypto/tinycrypt
      groups: [crypto]
      # 轻量级加密库，提供基础的加密算法实现，适用于资源受限的嵌入式设备

    # ========== BabbleSim 蓝牙仿真框架 ==========
    - name: babblesim_base
      remote: babblesim
      repo-path: base
      path: tools/bsim/components
      revision: 2cfac3dca2071452ae481d115d8541880568753d
      groups: [babblesim]
      # BabbleSim 仿真框架基础组件，用于蓝牙协议栈的仿真测试

    - name: babblesim_ext_2G4_channel_NtNcable
      remote: babblesim
      repo-path: ext_2G4_channel_NtNcable
      path: tools/bsim/components/ext_2G4_channel_NtNcable
      revision: 20a38c997f507b0aa53817aab3d73a462fff7af1
      groups: [babblesim]
      # 2.4GHz N对N有线信道模型，模拟多设备间的有线连接通信

    - name: babblesim_ext_2G4_channel_multiatt
      remote: babblesim
      repo-path: ext_2G4_channel_multiatt
      path: tools/bsim/components/ext_2G4_channel_multiatt
      revision: bde72a57384dde7a4310bcf3843469401be93074
      groups: [babblesim]
      # 多路径衰减信道模型，模拟真实射频环境中的信号衰减和干扰

    - name: babblesim_ext_2G4_device_WLAN_actmod
      remote: babblesim
      repo-path: ext_2G4_device_WLAN_actmod
      path: tools/bsim/components/ext_2G4_device_WLAN_actmod
      revision: 9cb6d8e72695f6b785e57443f0629a18069d6ce4
      groups: [babblesim]
      # WLAN 设备活动模型，模拟 WiFi 设备对蓝牙的干扰

    - name: babblesim_ext_2G4_device_burst_interferer
      remote: babblesim
      repo-path: ext_2G4_device_burst_interferer
      path: tools/bsim/components/ext_2G4_device_burst_interferer
      revision: 5b5339351d6e6a2368c686c734dc8b2fc65698fc
      groups: [babblesim]
      # 突发干扰器模型，模拟间歇性的射频干扰源

    - name: babblesim_ext_2G4_device_playback
      remote: babblesim
      repo-path: ext_2G4_device_playback
      path: tools/bsim/components/ext_2G4_device_playback
      revision: abb48cd71ddd4e2a9022f4bf49b2712524c483e8
      groups: [babblesim]
      # 回放设备模型，可以回放预录制的射频信号，用于重现特定测试场景

    - name: babblesim_ext_2G4_libPhyComv1
      remote: babblesim
      repo-path: ext_2G4_libPhyComv1
      path: tools/bsim/components/ext_2G4_libPhyComv1
      revision: e18e41e8e3fa9f996559ed98b9238a5702dcdd36
      groups: [babblesim]
      # 物理层通信库v1，提供 2.4GHz 物理层仿真的底层通信接口

    - name: babblesim_ext_2G4_modem_BLE_simple
      remote: babblesim
      repo-path: ext_2G4_modem_BLE_simple
      path: tools/bsim/components/ext_2G4_modem_BLE_simple
      revision: 4d2379de510684cd4b1c3bbbb09bce7b5a20bc1f
      groups: [babblesim]
      # 简化的 BLE 调制解调器模型，用于基础的蓝牙低功耗通信仿真

    - name: babblesim_ext_2G4_modem_magic
      remote: babblesim
      repo-path: ext_2G4_modem_magic
      path: tools/bsim/components/ext_2G4_modem_magic
      revision: edfcda2d3937a74be0a59d6cd47e0f50183453da
      groups: [babblesim]
      # 理想化的调制解调器模型，无射频损耗，用于协议层测试

    - name: babblesim_ext_2G4_phy_v1
      remote: babblesim
      repo-path: ext_2G4_phy_v1
      path: tools/bsim/components/ext_2G4_phy_v1
      revision: 8964ed1eb94606c2ea555340907bdc5171793e65
      groups: [babblesim]
      # 2.4GHz 物理层仿真引擎v1，核心的射频物理层仿真组件

    - name: babblesim_ext_libCryptov1
      remote: babblesim
      repo-path: ext_libCryptov1
      path: tools/bsim/components/ext_libCryptov1
      revision: da246018ebe031e4fe4a8228187fb459e9f3b2fa
      groups: [babblesim]
      # 加密库v1，为 BabbleSim 提供蓝牙安全相关的加密算法

    - name: bsim
      repo-path: babblesim-manifest
      revision: 2ba22a0608ad9f46da1b96ee5121af357053c791
      path: tools/bsim
      groups: [babblesim]
      # BabbleSim 主清单，整合所有 BabbleSim 组件

    # ========== ARM 相关库 ==========
    - name: cmsis
      revision: 512cc7e895e8491696b61f7ba8066b4a182569b8
      path: modules/hal/cmsis
      groups: [hal]
      # ARM CMSIS 标准接口，提供 Cortex-M 处理器的统一硬件抽象层

    - name: cmsis-dsp
      revision: d80a49b2bb186317dc1db4ac88da49c0ab77e6e7
      path: modules/lib/cmsis-dsp
      # ARM CMSIS DSP 库，提供优化的数字信号处理算法

    - name: cmsis-nn
      revision: e9328d612ea3ea7d0d210d3ac16ea8667c01abdd
      path: modules/lib/cmsis-nn
      # ARM CMSIS NN 库，提供神经网络和机器学习算法，用于 AI/ML 应用

    - name: cmsis_6
      repo-path: CMSIS_6
      revision: 06d952b6713a2ca41c9224a62075e4059402a151
      path: modules/hal/cmsis_6
      groups: [hal]
      # ARM CMSIS v6，最新版本的 CMSIS 标准

    # ========== 文件系统 ==========
    - name: fatfs
      revision: 16245c7c41d2b79e74984f49b5202551786b8a9b
      path: modules/fs/fatfs
      groups: [fs]
      # FAT 文件系统实现，支持 SD 卡、U盘等存储设备

    - name: littlefs
      path: modules/fs/littlefs
      groups: [fs]
      revision: 8f5ca347843363882619d8f96c00d8dbd88a8e79
      # 轻量级文件系统，专为嵌入式 Flash 存储设计，具备断电保护功能

    # ========== 硬件抽象层 (HAL) ==========
    - name: hal_adi
      revision: 16829b77264678f31a2d077a870af7bdca2d39bd
      path: modules/hal/adi
      groups: [hal]
      # Analog Devices (ADI) 芯片的硬件抽象层

    - name: hal_afbr
      revision: 4e1eea7ea283db9d9ce529b0e9f89c0b5c2660e3
      path: modules/hal/afbr
      groups: [hal]
      # AFBR 光纤通信芯片的硬件抽象层

    - name: hal_ambiq
      revision: 84ccbfc0b6041ba9f5688337c78bad99da5448ce
      path: modules/hal/ambiq
      groups: [hal]
      # Ambiq Apollo 超低功耗 MCU 的硬件抽象层

    - name: hal_atmel
      revision: ca7e4c6920f44b9d677ed5995ffa169f18a54cdf
      path: modules/hal/atmel
      groups: [hal]
      # Atmel/Microchip AVR 和 SAM 系列 MCU 的硬件抽象层

    - name: hal_bouffalolab
      path: modules/hal/bouffalolab
      revision: 5811738e2be348f30dc97d78280f2735d5d14084
      groups: [hal]
      # 博流智能 (Bouffalo Lab) 芯片的硬件抽象层，如 BL602/BL616 等 WiFi MCU

    - name: hal_espressif
      revision: f3453bdeced28642424692aae32cce4eec3f2d7f
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups: [hal]
      # Espressif ESP32 系列 WiFi/蓝牙 SoC 的硬件抽象层

    - name: hal_ethos_u
      revision: 50ddffca1cc700112f25ad9bc077915a0355ee5d
      path: modules/hal/ethos_u
      groups: [hal]
      # ARM Ethos-U NPU (神经网络处理单元) 的硬件抽象层，用于 AI 加速

    - name: hal_gigadevice
      revision: 2994b7dde8b0b0fa9b9c0ccb13474b6a486cddc3
      path: modules/hal/gigadevice
      groups: [hal]
      # 兆易创新 (GigaDevice) GD32 系列 MCU 的硬件抽象层

    - name: hal_infineon
      revision: 1030915af885cffc8cedc49a62291dd279a9e81e
      path: modules/hal/infineon
      groups: [hal]
      # 英飞凌 (Infineon) MCU 的硬件抽象层，如 PSoC 系列

    - name: hal_intel
      revision: 0447cd22e74d7ca243653f21cfd6e38c016630c6
      path: modules/hal/intel
      groups: [hal]
      # Intel 处理器和 SoC 的硬件抽象层

    - name: hal_microchip
      revision: 32a79d481c056b2204a5701d5a5799f9e5130dd7
      path: modules/hal/microchip
      groups: [hal]
      # Microchip PIC 和 SAM 系列 MCU 的硬件抽象层

    - name: hal_nordic
      revision: 9587b1dcb83d24ab74e89837843a5f7d573f7059
      path: modules/hal/nordic
      groups: [hal]
      # Nordic nRF 系列蓝牙 SoC 的硬件抽象层，如 nRF52/nRF53/nRF91

    - name: hal_nuvoton
      revision: be1042dc8a96ebe9ea4c5d714f07c617539106d6
      path: modules/hal/nuvoton
      groups: [hal]
      # 新唐科技 (Nuvoton) MCU 的硬件抽象层

    - name: hal_nxp
      revision: 7a52cbb7cb56db3a276cbd617db3ea7cc3435d12
      path: modules/hal/nxp
      groups: [hal]
      # NXP i.MX RT、Kinetis、LPC 系列 MCU 的硬件抽象层

    - name: hal_openisa
      revision: eabd530a64d71de91d907bad257cd61aacf607bc
      path: modules/hal/openisa
      groups: [hal]
      # OpenISA RISC-V 处理器的硬件抽象层

    - name: hal_quicklogic
      revision: bad894440fe72c814864798c8e3a76d13edffb6c
      path: modules/hal/quicklogic
      groups: [hal]
      # QuickLogic FPGA 和 SoC 的硬件抽象层

    - name: hal_renesas
      path: modules/hal/renesas
      revision: 0769fe1520f6c14e6301188588da758a609f181d
      groups: [hal]
      # 瑞萨电子 (Renesas) MCU 的硬件抽象层，如 RA、RZ 系列

    - name: hal_rpi_pico
      path: modules/hal/rpi_pico
      revision: 7b57b24588797e6e7bf18b6bda168e6b96374264
      groups: [hal]
      # 树莓派 Pico (RP2040) 的硬件抽象层

    - name: hal_silabs
      revision: 190a144a16bed9a938a94543ed5bbc70c0552e0f
      path: modules/hal/silabs
      groups: [hal]
      # Silicon Labs EFR32、EFM32 系列 MCU 的硬件抽象层

    - name: hal_st
      revision: 9f81b4427e955885398805b7bca0da3a8cd9109c
      path: modules/hal/st
      groups: [hal]
      # 意法半导体 (STMicroelectronics) STM32 系列 MCU 的硬件抽象层

    - name: hal_stm32
      revision: 1e753266ddfb4b07a8a0b1ec566e9637ea45d5ef
      path: modules/hal/stm32
      groups: [hal]
      # STM32 专用的扩展硬件抽象层

    - name: hal_tdk
      revision: 6727477af1e46fa43878102489b9672a9d24e39f
      path: modules/hal/tdk
      groups: [hal]
      # TDK 传感器和组件的硬件抽象层

    - name: hal_telink
      revision: 4226c7fc17d5a34e557d026d428fc766191a0800
      path: modules/hal/telink
      groups: [hal]
      # 泰凌微电子 (Telink) 蓝牙 SoC 的硬件抽象层

    - name: hal_ti
      revision: bc8e7b99bb668cc51a3aa384448a48c48a33f8e2
      path: modules/hal/ti
      groups: [hal]
      # 德州仪器 (TI) MCU 的硬件抽象层，如 CC26xx、MSP432 等

    - name: hal_wch
      revision: 6dd313768b5f4cc69baeac4ce6e59f2038eb8ce5
      path: modules/hal/wch
      groups: [hal]
      # 沁恒微电子 (WCH) MCU 的硬件抽象层，如 CH32V 系列 RISC-V MCU

    - name: hal_wurthelektronik
      revision: e3e2797b224fc48fdef1bc3e5a12a7c73108bba2
      path: modules/hal/wurthelektronik
      groups: [hal]
      # Würth Elektronik 电子组件的硬件抽象层

    - name: hal_xtensa
      revision: b38620c7cc61e349e192ed86a54940a5cd0636b7
      path: modules/hal/xtensa
      groups: [hal]
      # Cadence Xtensa 处理器架构的硬件抽象层

    - name: libmetal
      revision: 91d38634d1882f0a2151966f8c5c230ce1c0de7b
      path: modules/hal/libmetal
      groups: [hal]
      # 跨平台硬件抽象库，用于异构多核系统的底层硬件访问

    # ========== 网络协议栈 ==========
    - name: hostap
      path: modules/lib/hostap
      revision: e942f86e865d5b24bbbe8b0c333f030cbbe62bfb
      # WiFi 主机接入点 (hostapd) 和客户端 (wpa_supplicant) 实现

    - name: loramac-node
      revision: fb00b383072518c918e2258b0916c996f2d4eebe
      path: modules/lib/loramac-node
      # LoRaWAN 协议栈实现，用于 LoRa 低功耗广域网通信

    - name: openthread
      revision: 3ae741f95e7dfb391dec35c48742862049eb62e8
      path: modules/lib/openthread
      # OpenThread Thread 网络协议栈，用于 IPv6 物联网 mesh 网络

    - name: nrf_wifi
      revision: 5f59c2336c69f28ae83f93812a1d726f9fceabfe
      path: modules/lib/nrf_wifi
      # Nordic nRF WiFi 驱动和协议栈

    - name: uoscore-uedhoc
      revision: 54abc109c9c0adfd53c70077744c14e454f04f4a
      path: modules/lib/uoscore-uedhoc
      # uOSCORE 和 uEDHOC 安全协议实现，用于物联网设备间的安全通信

    # ========== 音频编解码 ==========
    - name: liblc3
      revision: 48bbd3eacd36e99a57317a0a4867002e0b09e183
      path: modules/lib/liblc3
      # LC3 低功耗音频编解码器，用于蓝牙 LE Audio

    - name: libsbc
      revision: 8e1beda02acb8972e29e6edbb423f7cafe16e445
      path: modules/lib/libsbc
      # SBC 音频编解码器，用于经典蓝牙 A2DP 音频传输

    # ========== 密码学和安全 ==========
    - name: mbedtls
      revision: 85440ef5fffa95d0e9971e9163719189cf34d979
      path: modules/crypto/mbedtls
      groups: [crypto]
      # Mbed TLS 加密库，提供 TLS/SSL、加密算法和 X.509 证书处理

    - name: trusted-firmware-a
      revision: 713ffbf96c5bcbdeab757423f10f73eb304eff07
      path: modules/tee/tf-a/trusted-firmware-a
      groups: [tee]
      # ARM Trusted Firmware-A，提供安全世界的引导和运行时服务

    - name: trusted-firmware-m
      revision: 021e2bbd50c215e41710a72e05abce3224f074a7
      path: modules/tee/tf-m/trusted-firmware-m
      groups: [tee]
      # ARM Trusted Firmware-M，为 ARMv8-M 架构提供可信执行环境 (TEE)

    # ========== 引导加载器 ==========
    - name: mcuboot
      revision: 4eba8087fa606db801455f14d185255bc8c49467
      path: bootloader/mcuboot
      groups: [bootloader]
      # MCUboot 安全引导加载器，支持固件更新、回滚保护和数字签名验证

    # ========== 多核和 IPC ==========
    - name: open-amp
      revision: c30a6d8b92fcebdb797fc1a7698e8729e250f637
      path: modules/lib/open-amp
      # OpenAMP 异构多核处理器间通信框架，支持 RPMsg 和共享内存通信

    - name: nrf_hw_models
      revision: 6e5961223f81aa2707c555db138819a5c1b7942c
      path: modules/bsim_hw_models/nrf_hw_models
      # Nordic nRF 硬件模型，用于 BabbleSim 仿真环境

    # ========== 数据序列化 ==========
    - name: zcbor
      revision: 9b07780aca6fb21f82a241ba386ad9b379809337
      path: modules/lib/zcbor
      # ZCBOR CBOR 编解码器，用于物联网数据序列化

    - name: libmctp
      revision: b97860e78998551af99931ece149eeffc538bdb1
      path: modules/lib/libmctp
      # MCTP (Management Component Transport Protocol) 实现，用于系统管理通信

    # ========== 用户界面 ==========
    - name: lvgl
      revision: b03edc8e6282a963cd312cd0b409eb5ce263ea75
      path: modules/lib/gui/lvgl
      # LVGL 轻量级图形用户界面库，支持触摸屏、按钮等交互组件

    # ========== 调试和分析工具 ==========
    - name: edtt
      revision: b9ca3c7c030518f07b7937dacf970d37a47865a76
      path: tools/edtt
      groups: [tools]
      # Embedded Device Test Tool，嵌入式设备测试工具

    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups: [debug]
      revision: 33e5c23cbedda5ba12dbe50c4baefb362a791001
      # MIPI System Trace 协议实现，用于系统级调试和性能分析

    - name: net-tools
      revision: 986bfeb040df3d9029366de8aea4ce1f84e93780
      path: tools/net-tools
      groups: [tools]
      # 网络测试和调试工具集

    - name: percepio
      path: modules/debug/percepio
      revision: 49e6dc202aa38c2a3edbafcc2dab85dec6aee973
      groups: [debug]
      # Percepio Tracealyzer 实时内核分析工具，用于 RTOS 性能调试

    - name: segger
      revision: cf56b1d9c80f81a26e2ac5727c9cf177116a4692
      path: modules/debug/segger
      groups: [debug]
      # SEGGER 调试工具支持，包括 J-Link、RTT 等调试接口

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
    # Zephyr RTOS 内核本身，提供实时操作系统核心功能
```
