### ISSUE TITLE
RT-THREAD scons命令汇总

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/bluetoothlover_doc#570]

**Comment by supperthomas** [comment]
scons --target=cmake
Scons --target=makefile
` Avaible targets: mdk, mdk4, mdk5, iar, vs, vs2012, vsc, cb, ua, cdk, makefile, eclipse, ses, cmake, cmake-armclang, xmake, codelite, esp-idf, zig`

**Comment by supperthomas** [comment]
`scons --verbose`

**Comment by supperthomas** [comment]
使用指令 scons --buildlib=xxx，其中 xxx 为 Group 的名字。

**Comment by supperthomas** [comment]
```
Local Options:
  --dist                      make distribution
  --dist-ide, --dist-rtstudio
                              make distribution for RT-Thread Studio IDE
  --project-path=PROJECT-PATH
                              set project output path
  --project-name=PROJECT-NAME
                              set project name
  --cscope                    Build Cscope cross reference database. Requires cscope installed.
  --clang-analyzer            Perform static analyze with Clang-analyzer. Requires Clang installed.It is recommended to use with scan-build like this:`scan-build scons --clang-analyzer`If things goes well, scan-build will instruct you to
                                invoke scan-view.
  --buildlib=BUILDLIB         building library of a component
  --cleanlib                  clean up the library by --buildlib
  --target=TARGET             set target project: mdk/mdk4/mdk5/iar/vs/vsc/ua/cdk/ses/makefile/eclipse/codelite/cmake
  --cmsispack=CMSISPACK       set pack: <cmsispack path>
  --strict                    Compiling project with strict mode and ALL warning will be errors
  --verbose                   print verbose information during build
  --cc-prefix=EXEC-PREFIX, --exec-prefix=EXEC-PREFIX
                              set RTT_CC_PREFIX temperately
  --cc-path=EXEC-PATH, --exec-path=EXEC-PATH
                              set RTT_EXEC_PATH temperately
  --stackanalysis             thread stack static analysis
  --genconfig                 Generate .config from rtconfig.h
  --useconfig=USECONFIG       make rtconfig.h from config file.
  --global-macros=GLOBAL-MACROS
                              attach global macros in the project. e.g. scons --global-config=RT_USING_XX,RT_USING_YY or scons --global-config="RT_USING_XX, RT_USING_YY"
  --reset-project-config      reset the project configurations to default
  --guiconfig, --pyconfig     Python GUI menuconfig for RT-Thread BSP
  --defconfig, --pyconfig-silent
                              Don`t show Python GUI menuconfig window
  --menuconfig                make menuconfig for RT-Thread BSP
  --cdb                       make compile_commands.json
```

**Comment by supperthomas** [comment]
`scons --genconfig` 根据`rtconfig.h`生成`.config`

**Comment by supperthomas** [comment]
`scons --pyconfig`  UI显示
保存最小配置
![image](https://github.com/user-attachments/assets/dd41d00e-251e-4b43-a331-763c310df220)

**Comment by supperthomas** [comment]
`scons --useconfig=fat.config` 根据.config生成rtconfig.h

**Comment by supperthomas** [comment]
`scons --global-macros=RT_USING_PIN` 编译的时候加宏

**Comment by supperthomas** [comment]
`scons --stackanalysis`  线程分析

**Comment by supperthomas** [comment]
`scons --defconfig`
==  `scons --pyconfig-silent`
编译不显示UI

**Comment by supperthomas** [comment]
`scons --cbd` 
生成
` compile_commands.json` 文件

**Comment by supperthomas** [comment]
```
name: ToolsCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - documentation/**
      - '**/README.md'
      - '**/README_zh.md'
      - '**/*.c'
      - '**/*.h'
      - '**/*.cpp'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: windows-latest

    name: Tools
    strategy:
      fail-fast: false
    env:
      TEST_BSP_ROOT: bsp/stm32/stm32f407-atk-explorer
    steps:
    - uses: actions/checkout@v4

    - name: Install Tools
      shell: powershell
      run: |
          wget https://raw.githubusercontent.com/RT-Thread/env/master/install_windows.ps1 -O install_windows.ps1
          set-executionpolicy remotesigned
          .\install_windows.ps1
          scons --version
```
