### ISSUE TITLE
github 上传产物

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/bluetoothlover_doc#583]
```
  # cd for test ouput
  collect-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: combined-output
        
      - name: Upload combined output as artifact
        uses: actions/upload-artifact@main
        with:
          name: combined-output
          path: combined-output/
```
